---

- name: Apply tunnel configuration
  ios_config:
    src: templates/wan/04-tunnel_interface.j2
    provider: "{{ ioscli }}"
  tags: tunnel
  register: tunnel_config_results

  
- set_fact: tunnel_config_changes={{ tunnel_config_results | to_nice_yaml }}
  