---

- hosts: iwan:lan

  tasks:

   - name: configure crypto key
     telnet:
       user: cisco
       password: cisco
       login_prompt: "Username: "
       prompts:
         - "[>|#]"
       command:
         - terminal length 0
         - configure terminal
         - crypto key generate rsa modulus 1024